base_url = "ams1.vultrobjects.com"
access_key = "S8HGHPW59BRPCKHGRF7E"
secret_key = "z7tiHwTaY635dX8p8kIuVUhnh0sq7RVZpX3Lpdqf"
sk_bs58 = "2bXwDnoKKrD2yEJ2jRMq3nMyiHhTkWpN8ADoXAhfdJcj"
pk_bs58 = "S3YaLN66ZWM3ZcNboV7utxWeaDUePitHonjRMe9aSNYrL34kxCj3xqzusKeDP74vXBgE2YgDzB76BUMW1XP22hzR"